/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import com.google.gson.Gson;

import java.io.*;
import java.util.Scanner;

public class App {

    public static void main(String[] args) throws IOException {
        ChristmasParty attackOfTheSweaters = new ChristmasParty("attack of the sweaters", "Star Wars Sweater", 9);
        System.out.println(attackOfTheSweaters);
        attackOfTheSweaters.party();
        Gson gson = new Gson();
        System.out.println(gson.toJson(attackOfTheSweaters));

        String stringyParty = gson.toJson(attackOfTheSweaters);
//        stringyParty.party()
//        File f = new File("src/main/resources/myParty.json");
//        FileWriter coolWriter = new FileWriter("src/main/resources/myParty.json");
//        gson.toJson(attackOfTheSweaters, coolWriter);
//        coolWriter.close();

        Scanner reader = new Scanner(new File("src/main/resources/myParty.json"));
        String firstLine = reader.nextLine();
        System.out.println("from a file" + firstLine);
        System.out.println(gson.fromJson(firstLine, ChristmasParty.class));

        ChristmasParty fromFileParty = gson.fromJson(firstLine, ChristmasParty.class);
        fromFileParty.party();

        System.out.println(gson.fromJson(firstLine, ComedyShow.class));
        System.out.println(gson.fromJson(firstLine, Dog.class));
        System.out.println(gson.fromJson(firstLine, Cat.class));
    }

}
