/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradlePractice;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    // write a method that takes in an array of strings and returns the longest string in that array
    public static String longString(String[] arr) {
        String answer = arr[0];
        for (int i = 1; i < arr.length; i++) {
            if (arr[i].length() > answer.length()) {
                answer = arr[i];
            }
        }
        return answer;
    }
}
