/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package alice;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {
    public static String[] characters = new String[]{"caterpillar", "cheshire", "alice", "queen", "hatter", "hare"};
    public String getGreeting() {
        return "Hello world.";
    }

    public static void findCommonAliceCharacters() {
        try{
            Scanner aliceReader = new Scanner(new File("alice.txt"));
            while(aliceReader.hasNext()) {
                System.out.println(aliceReader.next());
            }
        } catch(FileNotFoundException e) {
            System.out.println("could not find alice.txt");
        }
    }
    // read through alice in wonderland
    // each time we find one of these characters,
    // count it
    // at the end, show how often each character showed up
    public static void main(String[] args) {
        findCommonAliceCharacters();
    }
}
