/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package alice;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Scanner;

public class App {
    public static String[] characters = new String[]{"caterpillar", "cheshire", "alice", "queen", "hatter", "hare"};
    public String getGreeting() {
        return "Hello world.";
    }

    public static void findCommonAliceCharacters() {
        try{
            HashSet<String> characterSet = new HashSet<String>(Arrays.asList(characters));
            HashMap<String, Integer> characterCounts = new HashMap<>();
            for (String character : characters) {
                characterCounts.put(character, 0);
            }
            // file path starts at the same level as build.gradle
            Scanner aliceReader = new Scanner(new File("src/main/resources/alice.txt"));
            while(aliceReader.hasNext()) {
                String word = aliceReader.next().toLowerCase();
                // each time we find one of these characters,
                if(characterSet.contains(word)) {
                    // increment its count by 1
                    characterCounts.put(word, characterCounts.get(word) + 1);
                }

            }
            // at the end, show how often each character showed up
            for (String character : characterCounts.keySet()) {
                System.out.println( String.format("%s: %d", character, characterCounts.get(character)) );
            }
        } catch(FileNotFoundException e) {
            System.out.println("could not find alice.txt");
        }
    }
    // read through alice in wonderland

    public static void main(String[] args) {
        findCommonAliceCharacters();
    }
}
