/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package internetdemo;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;

public class App {
    public String getNumbersAPI() throws IOException {
        URL jqueryUrl = new URL("http://numbersapi.com/12/12/date");
        HttpURLConnection connection = (HttpURLConnection) jqueryUrl.openConnection();
        // this line of code actually takes like half a second
        // james says, "gross"
        BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
        StringBuilder data = new StringBuilder();
        String line = reader.readLine();
        while(line != null) {
            data.append(line);
            line = reader.readLine();
        }
        return data.toString();
    }

    public static void main(String[] args) {
        try {
            System.out.println(new App().getNumbersAPI());
        } catch (IOException e) {
            // there was no internet
            System.out.println("one is the loneliest number");
        }
    }
}
